version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: publisher
    ports:
      - "5400:5400"
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password
      - MESSAGE_QUEUE=message_queue
      - NOTIFICATION_QUEUE=notification_queue
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password
      - MESSAGE_QUEUE=message_queue
      - NOTIFICATION_QUEUE=notification_queue
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:




# docker exec -it rabbitmq bash